import{a as f,S as P,i as r}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=a(t);fetch(t.href,n)}})();const c=15;f.defaults.baseURL="https://pixabay.com";const S="/api/",q="42798997-7eb979f96087e0185c9def0a6";async function g(s,e){return await f.get(`${S}`,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:c,page:e}})}const p=document.querySelector(".gallery");function O(s){return s.map(e=>`<li class="gallery-item">
    <a href="${e.largeImageURL}" class="gallery-link">
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
    </a>
    <div class="gallery-container">
    <p class="gallery-text">Likes<span>${e.likes}</span></p>
      <p class="gallery-text">Views<span>${e.views}</span></p>
      <p class="gallery-text">Comments<span>${e.comments}</span></p>
      <p class="gallery-text">Downloads<span>${e.downloads}</span></p>
    </div>
  </li>`).join(" ")}function m(s){p.insertAdjacentHTML("beforeend",O(s))}const u=document.querySelector("form"),$=document.querySelector("input"),d=document.querySelector(".padding-button"),y=document.querySelector(".loader");let i=1;function x(s){const a=s.getBoundingClientRect().height*2;window.scrollBy({top:a,behavior:"smooth"})}function h(){y.classList.remove("is-hidden")}function w(){y.classList.add("is-hidden")}function B(){d.classList.remove("is-hidden")}function L(){d.classList.add("is-hidden")}function v(s,e){s<e&&(r.warning({message:"We are sorry, but youve reached the end of search results.!"}),L())}async function D(s){s.preventDefault(),i=1,h(),p.innerHTML="";const e=u.elements.field.value;if(e)try{const a=await g(e,i);a.data.total!==0?(m(a.data.hits),b.refresh(),B(),v(a.data.hits.length,c)):(r.warning({message:"Sorry, there are no images matching your search query. Please try again!"}),$.value="",L())}catch{r.warning({message:"Ups, something wrong bad. Please try again!"})}finally{w()}else r.warning({message:"Please enter the name of the picture!"})}async function E(s){i++,s.preventDefault(),h();const e=u.elements.field.value;try{const a=await g(e,i);m(a.data.hits),b.refresh();const o=document.querySelector(".gallery-item");x(o),v(a.data.hits.length,c)}catch{r.warning({message:"Ups, something wrong bad. Please try again!"})}finally{w()}}u.addEventListener("submit",D);d.addEventListener("click",E);const b=new P(".gallery a",{captionsData:"alt",captionDelay:"250"});
//# sourceMappingURL=commonHelpers.js.map
